"""add level and parent_code to location

Revision ID: 1ebf57213f41
Revises: f24a1ba219f2
Create Date: 2026-07-03 16:34:46.878564

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ebf57213f41'
down_revision: Union[str, Sequence[str], None] = 'f24a1ba219f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('location', sa.Column('level', sa.Enum('PROVINCE', 'CITY', 'DISTRICT', name='locationlevel'), nullable=False, server_default='PROVINCE', comment='层级：1省 2市 3区/县'))
    op.add_column('location', sa.Column('parent_code', sa.String(length=20), nullable=True, comment='上级地区编码，顶级为空'))
    op.create_index(op.f('ix_location_parent_code'), 'location', ['parent_code'], unique=False)
    op.create_foreign_key('fk_location_parent_code', 'location', 'location', ['parent_code'], ['code'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_location_parent_code', 'location', type_='foreignkey')
    op.drop_index(op.f('ix_location_parent_code'), table_name='location')
    op.drop_column('location', 'parent_code')
    op.drop_column('location', 'level')
    # ### end Alembic commands ###
