"""add status to posts

Revision ID: 4618b37ee422
Revises: b9067d2e46ea
Create Date: 2026-06-22 15:44:57.757122

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4618b37ee422'
down_revision: Union[str, Sequence[str], None] = 'b9067d2e46ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('status', sa.Enum('DRAFT', 'PUBLISHED', name='poststatus'), nullable=False, comment='状态'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'status')
    # ### end Alembic commands ###
