"""create likes table

Revision ID: 8c64bbe7cb36
Revises: 4618b37ee422
Create Date: 2026-06-26 09:03:31.344444

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '8c64bbe7cb36'
down_revision: Union[str, Sequence[str], None] = '4618b37ee422'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('likes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='用户ID'),
    sa.Column('post_id', sa.Integer(), nullable=False, comment='文章ID'),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'post_id', name='uniq_userid_postid')
    )
    op.create_index(op.f('ix_likes_post_id'), 'likes', ['post_id'], unique=False)
    op.create_index(op.f('ix_likes_user_id'), 'likes', ['user_id'], unique=False)
    op.alter_column('posts', 'create_time',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_comment='创建时间',
               existing_server_default=sa.text('(now())'))
    op.alter_column('posts', 'update_time',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_comment='更新时间',
               existing_server_default=sa.text('(now())'))
    op.alter_column('users', 'create_time',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_comment='创建时间',
               existing_server_default=sa.text('(now())'))
    op.alter_column('users', 'update_time',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_comment='更新时间',
               existing_server_default=sa.text('(now())'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'update_time',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_comment='更新时间',
               existing_server_default=sa.text('(now())'))
    op.alter_column('users', 'create_time',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_comment='创建时间',
               existing_server_default=sa.text('(now())'))
    op.alter_column('posts', 'update_time',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_comment='更新时间',
               existing_server_default=sa.text('(now())'))
    op.alter_column('posts', 'create_time',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_comment='创建时间',
               existing_server_default=sa.text('(now())'))
    op.drop_index(op.f('ix_likes_user_id'), table_name='likes')
    op.drop_index(op.f('ix_likes_post_id'), table_name='likes')
    op.drop_table('likes')
    # ### end Alembic commands ###
