"""create weahter table

Revision ID: e614ca23a52f
Revises: f6028d3c603a
Create Date: 2026-07-03 11:29:26.772916

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e614ca23a52f'
down_revision: Union[str, Sequence[str], None] = 'f6028d3c603a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('weather',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('location_id', sa.String(length=20), nullable=False, comment='地区ID'),
    sa.Column('temp', sa.Integer(), nullable=False, comment='温度'),
    sa.Column('feels_like', sa.Integer(), nullable=False, comment='体感温度'),
    sa.Column('text', sa.String(length=50), nullable=False, comment='天气现象'),
    sa.Column('wind_dir', sa.String(length=20), nullable=False, comment='风向'),
    sa.Column('wind_scale', sa.String(length=10), nullable=False, comment='风速'),
    sa.Column('humidity', sa.Integer(), nullable=False, comment='湿度'),
    sa.Column('obs_time', sa.DateTime(), nullable=False, comment='观测时间'),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('weather')
    # ### end Alembic commands ###
