"""create location table

Revision ID: f24a1ba219f2
Revises: e614ca23a52f
Create Date: 2026-07-03 15:38:07.202295

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f24a1ba219f2'
down_revision: Union[str, Sequence[str], None] = 'e614ca23a52f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('location',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('code', sa.String(length=20), nullable=False, comment='地区编码'),
    sa.Column('name', sa.String(length=50), nullable=False, comment='地区名称'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('location')
    # ### end Alembic commands ###
