"""create friendships table

Revision ID: f6028d3c603a
Revises: 8c64bbe7cb36
Create Date: 2026-06-26 16:22:10.794895

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f6028d3c603a'
down_revision: Union[str, Sequence[str], None] = '8c64bbe7cb36'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('friendship',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='用户ID'),
    sa.Column('friend_id', sa.Integer(), nullable=False, comment='好友ID'),
    sa.Column('status', sa.Enum('PENDING', 'ACCEPTED', 'REJECTED', name='friendstatus'), nullable=False, comment='状态'),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['friend_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'friend_id')
    )
    op.create_index(op.f('ix_friendship_friend_id'), 'friendship', ['friend_id'], unique=False)
    op.create_index(op.f('ix_friendship_user_id'), 'friendship', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_friendship_user_id'), table_name='friendship')
    op.drop_index(op.f('ix_friendship_friend_id'), table_name='friendship')
    op.drop_table('friendship')
    # ### end Alembic commands ###
